### ISSUE TITLE
DDPG action saturation 

### ISSUE THREAD

**Issue by wujingda** [ZhihanLee/DDPG_Learning#2]
李博士你好，我是看到你的github上ddpg/td3算法动作迅速saturation到最大值的疑问之后一路追到这里的。请问你最后解决这个问题了吗？我也是用DRL解决autonomous driving的博士生，可否交流一下，谢谢！

**Comment by ZhihanLee** [comment]
你好，感谢关注。我不是博士，只是小硕哈。关于动作饱和的问题，我的经验是它较多出现在actor网络多维动作输出的时候。
解决方法：第一个是状态归一化，这个在DL里面很常见，但是对于DRL可能还要额外加clip操作，当你估计有些输入状态会大于1的话，必须clip；第二是在网络里加批标准化层（batch normalization），这个不一定有效。

Thanks for your issue. From my experience, the solution to aciton saturation is normalization. 
Firstly, you should normalize your input state into [0,1] or [-1,1], if there is some 'error state input', clip function is also necessary to adopt, such as clip(state, 0, 1) or clip(state, -1, 1).
Secondly, batch normalization is optional, which needs you to add the batch normalization layer in the actor network. I can not guarantee this metohd works. But it is worthy to try.

**Comment by wujingda** [comment]
这是来自QQ邮箱的自动回复邮件。您好，您的邮件已经收到，谢谢。

**Comment by ZhihanLee** [comment]
你好，感谢关注。


我不是博士，只是小硕哈。关于动作饱和的问题，我的经验是它较多出现在actor网络多维动作输出的时候。
解决方法：第一个是状态归一化，这个在DL里面很常见，但是对于DRL可能还要额外加clip操作，当你估计有些输入状态会大于1的话，必须clip；第二是在网络里加批标准化层（batch normalization），这个不一定有效。


Thanks for your issue. From my experience, the solution to aciton saturation is normalization.&nbsp;
Firstly, you should normalize your input state into [0,1] or [-1,1], if there is some 'error state input', clip function is also necessary to adopt, such as clip(state, 0, 1) or clip(state, -1, 1).
Secondly, batch normalization is optional, which needs you to add the batch normalization layer in the actor network. I can not guarantee this metohd works. But it is worthy to try.



Regards

Zhihan&nbsp; Li

Postgraduate

Southeast University

Tel: 159-4520-3506

***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZhihanLee/DDPG_Learning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月27日(星期五) 晚上11:49
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ZhihanLee/DDPG_Learning] DDPG action saturation  (Issue #2)





 
李博士你好，我是看到你的github上ddpg/td3算法动作迅速saturation到最大值的疑问之后一路追到这里的。请问你最后解决这个问题了吗？我也是用DRL解决autonomous driving的博士生，可否交流一下，谢谢！

**Comment by wujingda** [comment]
好的，谢谢！我按照你的经验尝试一下！感谢感谢！
